// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// check_mhn_params_R
SEXP check_mhn_params_R(SEXP alpha, SEXP beta, SEXP gamma);
RcppExport SEXP _mhn_check_mhn_params_R(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(check_mhn_params_R(alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// convert_to_gw_R
Rcpp::List convert_to_gw_R(double alpha, double beta, double gamma);
RcppExport SEXP _mhn_convert_to_gw_R(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(convert_to_gw_R(alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// dmhn_cpp
Rcpp::NumericVector dmhn_cpp(Rcpp::NumericVector x, Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, bool log_p);
RcppExport SEXP _mhn_dmhn_cpp(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(dmhn_cpp(x, alpha, beta, gamma, log_p));
    return rcpp_result_gen;
END_RCPP
}
// mhn_mode_cpp
double mhn_mode_cpp(double alpha, double beta, double gamma);
RcppExport SEXP _mhn_mhn_mode_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(mhn_mode_cpp(alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// mhn_mean_cpp
double mhn_mean_cpp(double alpha, double beta, double gamma);
RcppExport SEXP _mhn_mhn_mean_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(mhn_mean_cpp(alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// mhn_var_cpp
double mhn_var_cpp(double alpha, double beta, double gamma);
RcppExport SEXP _mhn_mhn_var_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(mhn_var_cpp(alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// mhn_skewness_cpp
double mhn_skewness_cpp(double alpha, double beta, double gamma);
RcppExport SEXP _mhn_mhn_skewness_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(mhn_skewness_cpp(alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// mhn_kurtosis_cpp
double mhn_kurtosis_cpp(double alpha, double beta, double gamma);
RcppExport SEXP _mhn_mhn_kurtosis_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(mhn_kurtosis_cpp(alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// pmhn_cpp
Rcpp::NumericVector pmhn_cpp(Rcpp::NumericVector q, Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, bool lower_tail, bool log_p);
RcppExport SEXP _mhn_pmhn_cpp(SEXP qSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(pmhn_cpp(q, alpha, beta, gamma, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// pmhn_force_cpp
double pmhn_force_cpp(double q, double alpha, double beta, double gamma, std::string method);
RcppExport SEXP _mhn_pmhn_force_cpp(SEXP qSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(pmhn_force_cpp(q, alpha, beta, gamma, method));
    return rcpp_result_gen;
END_RCPP
}
// mhn_log_normalizing_const_R
double mhn_log_normalizing_const_R(double alpha, double beta, double gamma, double tol);
RcppExport SEXP _mhn_mhn_log_normalizing_const_R(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(mhn_log_normalizing_const_R(alpha, beta, gamma, tol));
    return rcpp_result_gen;
END_RCPP
}
// psi_series_R
double psi_series_R(double alpha, double beta, double gamma, double tol);
RcppExport SEXP _mhn_psi_series_R(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(psi_series_R(alpha, beta, gamma, tol));
    return rcpp_result_gen;
END_RCPP
}
// psi_integrate_R
double psi_integrate_R(double alpha, double beta, double gamma, double tol);
RcppExport SEXP _mhn_psi_integrate_R(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(psi_integrate_R(alpha, beta, gamma, tol));
    return rcpp_result_gen;
END_RCPP
}
// qmhn_cpp
Rcpp::NumericVector qmhn_cpp(Rcpp::NumericVector p, Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, bool lower_tail, bool log_p);
RcppExport SEXP _mhn_qmhn_cpp(SEXP pSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(qmhn_cpp(p, alpha, beta, gamma, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// rmhn_cpp
Rcpp::NumericVector rmhn_cpp(int n, Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, std::string method);
RcppExport SEXP _mhn_rmhn_cpp(SEXP nSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(rmhn_cpp(n, alpha, beta, gamma, method));
    return rcpp_result_gen;
END_RCPP
}
// rmhn_rtdr_cpp
Rcpp::NumericVector rmhn_rtdr_cpp(int n, double alpha, double beta, double gamma);
RcppExport SEXP _mhn_rmhn_rtdr_cpp(SEXP nSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(rmhn_rtdr_cpp(n, alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// dump_rtdr_envelope_cpp
Rcpp::List dump_rtdr_envelope_cpp(double alpha, double beta, double gamma);
RcppExport SEXP _mhn_dump_rtdr_envelope_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(dump_rtdr_envelope_cpp(alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// rtdr_contact_point_newton_test_cpp
Rcpp::List rtdr_contact_point_newton_test_cpp(double t_init, double log_dens_mode_val, double delta, std::string concavity, int max_iter);
RcppExport SEXP _mhn_rtdr_contact_point_newton_test_cpp(SEXP t_initSEXP, SEXP log_dens_mode_valSEXP, SEXP deltaSEXP, SEXP concavitySEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t_init(t_initSEXP);
    Rcpp::traits::input_parameter< double >::type log_dens_mode_val(log_dens_mode_valSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< std::string >::type concavity(concavitySEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(rtdr_contact_point_newton_test_cpp(t_init, log_dens_mode_val, delta, concavity, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// is_sqrt_gamma_R
bool is_sqrt_gamma_R(double gamma);
RcppExport SEXP _mhn_is_sqrt_gamma_R(SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(is_sqrt_gamma_R(gamma));
    return rcpp_result_gen;
END_RCPP
}
// is_truncated_normal_R
bool is_truncated_normal_R(double alpha);
RcppExport SEXP _mhn_is_truncated_normal_R(SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(is_truncated_normal_R(alpha));
    return rcpp_result_gen;
END_RCPP
}
// rmhn_sun_algo1_cpp
Rcpp::NumericVector rmhn_sun_algo1_cpp(int n, double alpha, double beta, double gamma);
RcppExport SEXP _mhn_rmhn_sun_algo1_cpp(SEXP nSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(rmhn_sun_algo1_cpp(n, alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// dump_sun_algo1_cpp
Rcpp::List dump_sun_algo1_cpp(double alpha, double beta, double gamma);
RcppExport SEXP _mhn_dump_sun_algo1_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(dump_sun_algo1_cpp(alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// rmhn_sun_algo3_cpp
Rcpp::NumericVector rmhn_sun_algo3_cpp(int n, double alpha, double beta, double gamma);
RcppExport SEXP _mhn_rmhn_sun_algo3_cpp(SEXP nSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(rmhn_sun_algo3_cpp(n, alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// dump_sun_algo3_cpp
Rcpp::List dump_sun_algo3_cpp(double alpha, double beta, double gamma);
RcppExport SEXP _mhn_dump_sun_algo3_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(dump_sun_algo3_cpp(alpha, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}
// rtnorm_robert_cpp
Rcpp::NumericVector rtnorm_robert_cpp(int n, double mu, double sigma);
RcppExport SEXP _mhn_rtnorm_robert_cpp(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rtnorm_robert_cpp(n, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mhn_check_mhn_params_R", (DL_FUNC) &_mhn_check_mhn_params_R, 3},
    {"_mhn_convert_to_gw_R", (DL_FUNC) &_mhn_convert_to_gw_R, 3},
    {"_mhn_dmhn_cpp", (DL_FUNC) &_mhn_dmhn_cpp, 5},
    {"_mhn_mhn_mode_cpp", (DL_FUNC) &_mhn_mhn_mode_cpp, 3},
    {"_mhn_mhn_mean_cpp", (DL_FUNC) &_mhn_mhn_mean_cpp, 3},
    {"_mhn_mhn_var_cpp", (DL_FUNC) &_mhn_mhn_var_cpp, 3},
    {"_mhn_mhn_skewness_cpp", (DL_FUNC) &_mhn_mhn_skewness_cpp, 3},
    {"_mhn_mhn_kurtosis_cpp", (DL_FUNC) &_mhn_mhn_kurtosis_cpp, 3},
    {"_mhn_pmhn_cpp", (DL_FUNC) &_mhn_pmhn_cpp, 6},
    {"_mhn_pmhn_force_cpp", (DL_FUNC) &_mhn_pmhn_force_cpp, 5},
    {"_mhn_mhn_log_normalizing_const_R", (DL_FUNC) &_mhn_mhn_log_normalizing_const_R, 4},
    {"_mhn_psi_series_R", (DL_FUNC) &_mhn_psi_series_R, 4},
    {"_mhn_psi_integrate_R", (DL_FUNC) &_mhn_psi_integrate_R, 4},
    {"_mhn_qmhn_cpp", (DL_FUNC) &_mhn_qmhn_cpp, 6},
    {"_mhn_rmhn_cpp", (DL_FUNC) &_mhn_rmhn_cpp, 5},
    {"_mhn_rmhn_rtdr_cpp", (DL_FUNC) &_mhn_rmhn_rtdr_cpp, 4},
    {"_mhn_dump_rtdr_envelope_cpp", (DL_FUNC) &_mhn_dump_rtdr_envelope_cpp, 3},
    {"_mhn_rtdr_contact_point_newton_test_cpp", (DL_FUNC) &_mhn_rtdr_contact_point_newton_test_cpp, 5},
    {"_mhn_is_sqrt_gamma_R", (DL_FUNC) &_mhn_is_sqrt_gamma_R, 1},
    {"_mhn_is_truncated_normal_R", (DL_FUNC) &_mhn_is_truncated_normal_R, 1},
    {"_mhn_rmhn_sun_algo1_cpp", (DL_FUNC) &_mhn_rmhn_sun_algo1_cpp, 4},
    {"_mhn_dump_sun_algo1_cpp", (DL_FUNC) &_mhn_dump_sun_algo1_cpp, 3},
    {"_mhn_rmhn_sun_algo3_cpp", (DL_FUNC) &_mhn_rmhn_sun_algo3_cpp, 4},
    {"_mhn_dump_sun_algo3_cpp", (DL_FUNC) &_mhn_dump_sun_algo3_cpp, 3},
    {"_mhn_rtnorm_robert_cpp", (DL_FUNC) &_mhn_rtnorm_robert_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_mhn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
