# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.check_mhn_params <- function(alpha, beta, gamma) {
    .Call(`_mhn_check_mhn_params_R`, alpha, beta, gamma)
}

.convert_to_gw <- function(alpha, beta, gamma) {
    .Call(`_mhn_convert_to_gw_R`, alpha, beta, gamma)
}

.dmhn_cpp <- function(x, alpha, beta, gamma, log_p) {
    .Call(`_mhn_dmhn_cpp`, x, alpha, beta, gamma, log_p)
}

.mhn_mode_cpp <- function(alpha, beta, gamma) {
    .Call(`_mhn_mhn_mode_cpp`, alpha, beta, gamma)
}

.mhn_mean_cpp <- function(alpha, beta, gamma) {
    .Call(`_mhn_mhn_mean_cpp`, alpha, beta, gamma)
}

.mhn_var_cpp <- function(alpha, beta, gamma) {
    .Call(`_mhn_mhn_var_cpp`, alpha, beta, gamma)
}

.mhn_skewness_cpp <- function(alpha, beta, gamma) {
    .Call(`_mhn_mhn_skewness_cpp`, alpha, beta, gamma)
}

.mhn_kurtosis_cpp <- function(alpha, beta, gamma) {
    .Call(`_mhn_mhn_kurtosis_cpp`, alpha, beta, gamma)
}

.pmhn_cpp <- function(q, alpha, beta, gamma, lower_tail, log_p) {
    .Call(`_mhn_pmhn_cpp`, q, alpha, beta, gamma, lower_tail, log_p)
}

.pmhn_force_cpp <- function(q, alpha, beta, gamma, method) {
    .Call(`_mhn_pmhn_force_cpp`, q, alpha, beta, gamma, method)
}

.mhn_log_normalizing_const <- function(alpha, beta, gamma, tol = -1.0) {
    .Call(`_mhn_mhn_log_normalizing_const_R`, alpha, beta, gamma, tol)
}

.psi_series <- function(alpha, beta, gamma, tol = -1.0) {
    .Call(`_mhn_psi_series_R`, alpha, beta, gamma, tol)
}

.psi_integrate <- function(alpha, beta, gamma, tol = -1.0) {
    .Call(`_mhn_psi_integrate_R`, alpha, beta, gamma, tol)
}

.qmhn_cpp <- function(p, alpha, beta, gamma, lower_tail, log_p) {
    .Call(`_mhn_qmhn_cpp`, p, alpha, beta, gamma, lower_tail, log_p)
}

.rmhn_cpp <- function(n, alpha, beta, gamma, method) {
    .Call(`_mhn_rmhn_cpp`, n, alpha, beta, gamma, method)
}

.rmhn_rtdr_cpp <- function(n, alpha, beta, gamma) {
    .Call(`_mhn_rmhn_rtdr_cpp`, n, alpha, beta, gamma)
}

.dump_rtdr_envelope_cpp <- function(alpha, beta, gamma) {
    .Call(`_mhn_dump_rtdr_envelope_cpp`, alpha, beta, gamma)
}

.rtdr_contact_point_newton_test_cpp <- function(t_init, log_dens_mode_val, delta, concavity, max_iter) {
    .Call(`_mhn_rtdr_contact_point_newton_test_cpp`, t_init, log_dens_mode_val, delta, concavity, max_iter)
}

.is_sqrt_gamma <- function(gamma) {
    .Call(`_mhn_is_sqrt_gamma_R`, gamma)
}

.is_truncated_normal <- function(alpha) {
    .Call(`_mhn_is_truncated_normal_R`, alpha)
}

.rmhn_sun_algo1_cpp <- function(n, alpha, beta, gamma) {
    .Call(`_mhn_rmhn_sun_algo1_cpp`, n, alpha, beta, gamma)
}

.dump_sun_algo1_cpp <- function(alpha, beta, gamma) {
    .Call(`_mhn_dump_sun_algo1_cpp`, alpha, beta, gamma)
}

.rmhn_sun_algo3_cpp <- function(n, alpha, beta, gamma) {
    .Call(`_mhn_rmhn_sun_algo3_cpp`, n, alpha, beta, gamma)
}

.dump_sun_algo3_cpp <- function(alpha, beta, gamma) {
    .Call(`_mhn_dump_sun_algo3_cpp`, alpha, beta, gamma)
}

.rtnorm_robert_cpp <- function(n, mu, sigma) {
    .Call(`_mhn_rtnorm_robert_cpp`, n, mu, sigma)
}

